CREATE TABLE BAG_DISCIPLINE
(
  ID BIGINT PRIMARY KEY NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255)
);
CREATE UNIQUE INDEX "UN_DISCIPLINE_NAME" ON BAG_DISCIPLINE (NAME);

CREATE SEQUENCE BAG_SEQUENCE INCREMENT BY 1 MINVALUE 1000;