CREATE TABLE BAG_SUBJECT
(
  ID BIGINT PRIMARY KEY NOT NULL,
  NAME VARCHAR(120) NOT NULL,
  DESCRIPTION VARCHAR(255),
  DISCIPLINE_ID BIGINT NOT NULL
);

ALTER TABLE BAG_SUBJECT ADD CONSTRAINT FK_SUBJECT_DISCIPLINE FOREIGN KEY (DISCIPLINE_ID) REFERENCES BAG_DISCIPLINE (ID);

CREATE INDEX IDX_SUBJECT_DISCIPLINE ON BAG_SUBJECT USING BTREE (DISCIPLINE_ID);