CREATE TABLE BAG_QUESTION
(
  ID BIGINT PRIMARY KEY NOT NULL,
  BODY TEXT NOT NULL,
  DOCUMENT_BODY TEXT,
  PRESENTATION_BODY TEXT,
  SOLUTION TEXT,
  DOCUMENT_SOLUTION TEXT,
  QUESTION_TYPE VARCHAR(30) NOT NULL,
  QUESTION_SOURCE_ID BIGINT
);

ALTER TABLE BAG_QUESTION ADD CONSTRAINT FK_QUESTION_SOURCE FOREIGN KEY (QUESTION_SOURCE_ID) REFERENCES BAG_QUESTION_SOURCE (ID);

CREATE INDEX IDX_QUESTION_SOURCE ON BAG_QUESTION USING BTREE (QUESTION_SOURCE_ID);

CREATE TABLE BAG_QUESTION_DISCIPLINE
(
  QUESTION_ID BIGINT NOT NULL,
  DISCIPLINE_ID BIGINT NOT NULL
);

ALTER TABLE BAG_QUESTION_DISCIPLINE ADD CONSTRAINT FK_QUESTION_DISCIPLINE_QUEST FOREIGN KEY (QUESTION_ID) REFERENCES BAG_QUESTION (ID) ON DELETE CASCADE;

CREATE INDEX IDX_QUESTION_DISCIPLINE_QUEST ON BAG_QUESTION_DISCIPLINE USING BTREE (QUESTION_ID);

ALTER TABLE BAG_QUESTION_DISCIPLINE ADD CONSTRAINT FK_QUESTION_DISCIPLINE_DISC FOREIGN KEY (DISCIPLINE_ID) REFERENCES BAG_DISCIPLINE (ID) ON DELETE CASCADE ;

CREATE INDEX IDX_QUESTION_DISCIPLINE_DISC ON BAG_QUESTION_DISCIPLINE USING BTREE (DISCIPLINE_ID);

CREATE UNIQUE INDEX "UN_QUESTION_DISCIPLINE" ON BAG_QUESTION_DISCIPLINE (QUESTION_ID, DISCIPLINE_ID);

CREATE TABLE BAG_QUESTION_SUBJECT
(
  QUESTION_ID BIGINT NOT NULL,
  SUBJECT_ID BIGINT NOT NULL
);

ALTER TABLE BAG_QUESTION_SUBJECT ADD CONSTRAINT FK_QUESTION_SUBJECT_QUEST FOREIGN KEY (QUESTION_ID) REFERENCES BAG_QUESTION (ID) ON DELETE CASCADE;

CREATE INDEX IDX_QUESTION_SUBJECT_QUEST ON BAG_QUESTION_SUBJECT USING BTREE (QUESTION_ID);

ALTER TABLE BAG_QUESTION_SUBJECT ADD CONSTRAINT FK_QUESTION_SUBJECT_SUB FOREIGN KEY (SUBJECT_ID) REFERENCES BAG_SUBJECT (ID);

CREATE INDEX IDX_QUESTION_SUBJECT_SUB ON BAG_QUESTION_SUBJECT USING BTREE (SUBJECT_ID);

CREATE UNIQUE INDEX "UN_QUESTION_SUBJECT" ON BAG_QUESTION_SUBJECT (QUESTION_ID, SUBJECT_ID);

CREATE TABLE BAG_ANSWER_OPTION
(
  ID BIGINT PRIMARY KEY NOT NULL,
  IS_RIGHT BOOLEAN,
  BODY TEXT NOT NULL,
  DOCUMENT_BODY TEXT,
  QUESTION_ID BIGINT NOT NULL
);

ALTER TABLE BAG_ANSWER_OPTION ADD CONSTRAINT FK_ANSWER_OPTION_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES BAG_QUESTION (ID) ON DELETE CASCADE;

CREATE INDEX IDX_ANSWER_OPTION_QUESTION ON BAG_ANSWER_OPTION USING BTREE (QUESTION_ID);