CREATE TABLE BAG_QUESTION_SOURCE
(
  ID BIGINT PRIMARY KEY NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255)
);

CREATE UNIQUE INDEX "UN_QUESTION_SOURCE_NAME" ON BAG_QUESTION_SOURCE (NAME);

